name: 'Emby Plugin'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Patch version
        run: sed -i "/FileVersion/s/.0</.$GITHUB_RUN_NUMBER</" **/*.csproj
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: .NET Publish
        run: dotnet publish --configuration Release --output publish Emby.Plugin.Bangumi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Emby.Plugin.Bangumi
          path: publish/Emby.Plugin.Bangumi.dll
